### ISSUE TITLE
mintItem now failing

### ISSUE THREAD

**Issue by dcsan** [GraphemeNFT/rarible-scaffold#5]
I merged my branch with rarible-scaffold, and now `yarn mint` seems to fail.

for local dev our environments are all different and YET a lot of config settings are checked into various source files, making it really messy to work together.

steps:
```
yarn compile
yarn deploy
```
get contract ID add to 
 
contracts/YourCollectible.address.js

```
yarn mint
```

fails. looking at methods in compiled contract that method isn't there.

**Comment by dcsan** [comment]
```js
  functions: {
    'approve(address,uint256)': [Function (anonymous)],
    'balanceOf(address)': [Function (anonymous)],
    'baseURI()': [Function (anonymous)],
    'getApproved(uint256)': [Function (anonymous)],
    'getCharacterIdentifier(uint256)': [Function (anonymous)],
    'isApprovedForAll(address,address)': [Function (anonymous)],
    'name()': [Function (anonymous)],
    'ownerOf(uint256)': [Function (anonymous)],
    'rollToMint(address)': [Function (anonymous)],
    'safeTransferFrom(address,address,uint256)': [Function (anonymous)],
    'safeTransferFrom(address,address,uint256,bytes)': [Function (anonymous)],
    'setApprovalForAll(address,bool)': [Function (anonymous)],
    'supportsInterface(bytes4)': [Function (anonymous)],
    'symbol()': [Function (anonymous)],
    'tokenByIndex(uint256)': [Function (anonymous)],
    'tokenOfOwnerByIndex(address,uint256)': [Function (anonymous)],
    'tokenURI(uint256)': [Function (anonymous)],
    'totalSupply()': [Function (anonymous)],
    'transferFrom(address,address,uint256)': [Function (anonymous)],
    approve: [Function (anonymous)],
    balanceOf: [Function (anonymous)],
    baseURI: [Function (anonymous)],
    getApproved: [Function (anonymous)],
    getCharacterIdentifier: [Function (anonymous)],
    isApprovedForAll: [Function (anonymous)],
    name: [Function (anonymous)],
    ownerOf: [Function (anonymous)],
    rollToMint: [Function (anonymous)],
    setApprovalForAll: [Function (anonymous)],
    supportsInterface: [Function (anonymous)],
    symbol: [Function (anonymous)],
    tokenByIndex: [Function (anonymous)],
    tokenOfOwnerByIndex: [Function (anonymous)],
    tokenURI: [Function (anonymous)],
    totalSupply: [Function (anonymous)],
    transferFrom: [Function (anonymous)]
  },

Uploading buffalo...
Minting buffalo with IPFS hash (QmXXrD3nqLm9GYr1z9Zv8tHTRNcthMVcWU3LQnuqtSmMGJ)
TypeError: yourCollectible.mintItem is not a function
    at main (/Users/dc/dev/crypto/graphemeNFT/rarible-scaffold/packages/hardhat/scripts/mint.js:50:25)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /usr/local/bin/node
Arguments: /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js mint
Directory: /Users/dc/dev/crypto/graphemeNFT/rarible-scaffold/packages/hardhat
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
➜  rarible-scaffold git:(letters)

```

**Comment by dcsan** [comment]
do i need to manually update an ABI file or something else to update the contract?
it has `rollToMint` but not `mintItem`

**Comment by dcsan** [comment]
oh `mintItem` is now NOT public?

and `rollToMint` takes different params

so the `yarn mint` script was checked in broken.

```
  await yourCollectible.rollToMint(toAddress, { gasLimit: 400000 })
```

changed and now it works

**Comment by tomosaigon** [comment]
Works
