### ISSUE TITLE
app broken

### ISSUE THREAD

**Issue by dcsan** [GraphemeNFT/rarible-scaffold#7]
I tried to use the "local" branch and just get no results. i d k if it ever worked.

just super cryptic errors

![image](https://user-images.githubusercontent.com/514002/130737116-be93c565-17f5-4b4b-ab44-ccf43fb45c5e.png)

minting server side

```
eth_accounts
eth_gasPrice
eth_sendTransaction
  Transaction: 0x54735c1ab0c9bb0798462b560008a97b272c5ce99f9e7486faf16db7fefb5338
  From:        0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:          0x9fe46736679d2d9a65f0992f2272de9f3c7fa6e0
  Value:       0 ETH
  Gas used:    21432 of 400000
  Block #6:    0xdcf0dee18ad703d13721304b1139adfb13a9a63f61ac89862790be13db76b977

eth_chainId
eth_getTransactionByHash
eth_blockNumber
eth_chainId
eth_blockNumber
eth_getLogs
eth_getBalance (2)
eth_accounts (2)
eth_call
  WARNING: Calling an account which is not a contract
  From:        0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:          0x9fe46736679d2d9a65f0992f2272de9f3c7fa6e0

eth_blockNumber
eth_getBlockByNumber
eth_blockNumber (2)


```

not sure what this means:

```
  WARNING: Calling an account which is not a contract
  From:        0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:          0x9fe46736679d2d9a65f0992f2272de9f3c7fa6e0
```

`to` is the 

/graphemeNFT/rarible-scaffold/packages/react-app/src/contracts/YourContract.address.js

**Comment by dcsan** [comment]
tempted to move back to the branch I got working, this branch seems just overly screwed up

**Comment by dcsan** [comment]
i suspect this `local` branch isn't fully working and something in the rarible fork is dependent on their protocol or whatever.

**Comment by tomosaigon** [comment]
There was a change to the contract that affected calls to mint. I made a quick fix https://github.com/GraphemeNFT/rarible-scaffold/commit/d34fe4dd92bd7cc3fe44829aaff8c5571f5b68a4

I think the rarible-starter-app branch is still broken so I abandoned it.

**Comment by dcsan** [comment]
I still get the same client error when trying to mint from client:


![image](https://user-images.githubusercontent.com/514002/130789839-b359706e-aecb-4ac9-bd97-cbc268bae0fc.png)

```
eth_gasPrice
eth_sendTransaction
  Contract call:       YourCollectible#rollToMint
  Transaction:         0x5dc83d89cb7bc12e0b2fc601b69af5e7987755e11148c4656c8df1cfb742ba92
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0xcf7ed3acca5a467e9e704c703e8d87f634fb0fc9
  Value:               0 ETH
  Gas used:            400000 of 400000
  Block #5:            0x47450bec9cffbe14f816527f6b778f6071f30037ab552d385958fd535fbf656e

  TransactionExecutionError: Transaction ran out of gas
      at HardhatNode._manageErrors (/Users/dc/dev/crypto/graphemeNFT/rarible-scaffold/packages/hardhat/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1178:14)
      at HardhatNode._gatherTraces (/Users/dc/dev/crypto/graphemeNFT/rarible-scaffold/packages/hardhat/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:935:30)
      at HardhatNode._mineBlockWithPendingTxs (/Users/dc/dev/crypto/graphemeNFT/rarible-scaffold/packages/hardhat/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1003:21)
      at HardhatNode.mineBlock (/Users/dc/dev/crypto/graphemeNFT/rarible-scaffold/packages/hardhat/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:321:16)
      at EthModule._sendTransactionAndReturnHash (/Users/dc/dev/crypto/graphemeNFT/rarible-scaffold/packages/hardhat/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1223:18)
      at HardhatNetworkProvider._sendWithLogging (/Users/dc/dev/crypto/graphemeNFT/rarible-scaffold/packages/hardhat/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:118:22)
      at HardhatNetworkProvider.request (/Users/dc/dev/crypto/graphemeNFT/rarible-scaffold/packages/hardhat/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:98:18)
      at JsonRpcHandler._handleRequest (/Users/dc/dev/crypto/graphemeNFT/rarible-scaffold/packages/hardhat/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:187:20)
      at JsonRpcHandler._handleSingleRequest (/Users/dc/dev/crypto/graphemeNFT/rarible-scaffold/packages/hardhat/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:166:17)
      at Server.JsonRpcHandler.handleHttp (/Users/dc/dev/crypto/graphemeNFT/rarible-scaffold/packages/hardhat/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:51:21)
```


now I get a new server error on `yarn mint` :

```
Uploading buffalo...
Minting buffalo with IPFS hash (QmXXrD3nqLm9GYr1z9Zv8tHTRNcthMVcWU3LQnuqtSmMGJ)
ProviderError: Transaction ran out of gas
    at HttpProvider.request (/Users/dc/dev/crypto/graphemeNFT/rarible-scaffold/packages/hardhat/node_modules/hardhat/src/internal/core/providers/http.ts:46:19)
    at GanacheGasMultiplierProvider.request (/Users/dc/dev/crypto/graphemeNFT/rarible-scaffold/packages/hardhat/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:170:34)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /usr/local/bin/node
Arguments: /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js mint
Directory: /Users/dc/dev/crypto/graphemeNFT/rarible-scaffold/packages/hardhat
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by dcsan** [comment]
mostly fixed. a failing tx was blocking
